""" Robot and control constants. """

LEFT_MOTOR_1_ID = 1
LEFT_MOTOR_2_ID = 3
RIGHT_MOTOR_1_ID = 2
RIGHT_MOTOR_2_ID = 0

PITCH_MOTOR_ID = 42

DRIVE_JOYSTICK_PORT = 0


FIRE_UPPER_BUTTON_ID = 1
FIRE_LOWER_BUTTON_ID = 2

PNEUMATIC_HUB_PORT = 1
UPPER_SOLENOID_1_CHANNEL = 0
UPPER_SOLENOID_2_CHANNEL = 1
UPPER_SOLENOID_3_CHANNEL = 2
LOWER_SOLENOID_1_CHANNEL = 3
LOWER_SOLENOID_2_CHANNEL = 4
LOWER_SOLENOID_3_CHANNEL = 5

SOLENOID_PULSE_LENGTH = 0.3
